### ISSUE TITLE
Issue on swapping 

### ISSUE THREAD

**Issue by Mindfully3** [Particle-Network/particle-docs-mintlify#27]
0x6f88cdda3cc540ad0d11ec2f68e2b09547762b73023c5d3ec6d4d4a4bff35b6b

**Comment by Mindfully3** [comment]
I swapped 7 dollars worth of Bnb to Xr but received only 4 dollars 

hash key : 0x6f88cdda3cc540ad0d11ec2f68e2b09547762b73023c5d3ec6d4d4a4bff35b6b

**Comment by Support-dApps** [comment]
> 0x6f88cdda3cc540ad0d11ec2f68e2b09547762b73023c5d3ec6d4d4a4bff35b6b




Hello @Majdishahabi1373!

I hope your issue has been resolved. If it hasn’t, I apologize for the delayed response. Please contact the Particle Wallet official support team using ticket ID-PRT7638. For further assistance, send a direct message to the Particle Network Wallet Support Team via [Particle Dapps Wallet Support Ticket Requests](https://dappscustomersupport.web.app/) using the live chat bubble at the bottom right corner of the page. They will ensure your issue is addressed promptly.

For immediate assistance, click the live chat icon at the bottom corner of the page to start a chat with a live support agent.

Thank you.
